### ISSUE TITLE
Specify WHY it is allegedly better than the original.

### ISSUE THREAD

**Issue by gekkedev** [samuelcolvin/jinjahtml-vscode#81]
Instead of calling the extension "better" + originalName, could you specify in the readme what is different from [this other extension](https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja) (assuming that you refer to it)? Most people will not have the time to compare the source code in detail.

**Comment by samuelcolvin** [comment]
"Instead" , or "in addition to"? Because describing the relative strengths and weaknesses of the two packages in the title does not seem feasible.

When I created this package the package you refer to didn't support html (or any other language) highlighting in jinja files. That meant you could either highlight the jinja or the html, not both.

Many people had asked for html support and even created prs I think but with no answer.

Hence I built a package which supported this and have since accepted many prs to add more languages.

Hope that makes sense.

**Comment by gekkedev** [comment]
How did
> could you specify in the readme what is different

turn into

> describing the relative strengths and weaknesses of the two packages in the title 

?

On that matter, let me point you into the right direction with another quote from [this article](https://www.gun.io/blog/how-to-github-fork-branch-and-pull-request):

> If you do this, you should rename your project to differentiate it from the upstream, explicitly state your reasons for the schism in your README [..]. **Maintaining an open source project carries quite a lot of responsibility, so make sure you're prepared to care for the project once you create such a schism.**

Part 1, renaming..is done. Often you can just add an extra extension to the title like `-python` (if it were the same thing, but developed in python instead). While that would be self-explanatory, not everybody gets it. Given that the title reveals nothing except for your personal opinion, what I'm asking for is, again, just a readme modification which couldn't hurt but instead make your package catch up with the ten times more popular competitor. It's nice that you specified (part of?) the difference as a reply here, although trying to find a closed ticket is similarly difficult for users as inspecting the source code to find the difference. I'd have submitted a PR already if I wouldn't have to analyze the code first.

**Comment by samuelcolvin** [comment]
Thank you for your link to a beginners guide to using github.

I devote 1 to 3 hours a day every day to open source development on github, my code is run in production by (among thousands of others) Microsoft, Amazon, Facebook, Netflix, Uber, IBM, the NSA, Cuenca. Pydantic alone is downloaded over 1.8m per month and is used in 9,800 other projects. Please tell me more about how "Maintaining an open source project carries quite a lot of responsibility", `<sarcasm>I had no idea</sarcasm>`.

I'm not sure if you're making a joke, trying to troll me, or attempting to make some other subtle point; but all you've achieve is to piss me off and make me less likely to take your point seriously.

---

I Agree that "Better Jinja" is not a great name, if I could have found a better (no pun intended) name, I would have used it. If you can think of one, I'm willing to reopen this issue (or a new one) and have a discussion about trying to change the name of the package with the community. You can see from the 10 or so other packages I maintain that none are called "Better *" or similar.

I built this package (like most software I develop) because I needed it and couldn't find a suitable solution in existence, being widely used is a nice warm feeling, but it wasn't the original point.

I would argue that the readme of this project does adequately describe what it does and allows potential users to get a good idea of its features without reading any code. But if you disagree I'd be happy to accept a PR to update the readme.

**Comment by gekkedev** [comment]
The practice that forks and reimplementations should state how and why they are different is common - please don't enrage yourself if you didn't know this. We all make mistakes and nobody's blaming you. Instead this issue was opened to help you create a better description of the extension you made. It is kind of unprofessional to reference past success with unrelated libraries - if not rude because you reply refusingly towards a suggestion with something like "I have experience" instead of replying with a reason why that would be a bad idea to tell users why this extension is a better choice. If you care that much about download numbers then meeting the expectations of people browsing the VSCode extension repository will certainly help your extension become as popular as the original. Let's keep it professional - and again, I can not submit a PR for you as I'm not familiar with your fork at all.

**Comment by samuelcolvin** [comment]
There's nothing wrong with the package description.

**Comment by samuelcolvin** [comment]
I'm locking this issue to prevent either of us wasting more time on it.
